["tools"]
# Note that for storm, we ask for the path to the binary
storm = "/path/to/storm/binary/storm"
# For prism, we ask the location of the directory.
prism = "/path/to/prism/directory"
# For modest, we ask for the path to the binary
modest = "/path/to/modest/binary/modest"

["byproducts"]
tmpfolder = "/tmp"
cleanup = 1