["tools"]
# Note that for storm, we ask for the path to the binary
storm = "/opt/storm/build/bin/storm"
# For prism, we ask the location of the directory.
prism = "/opt/prism/"
modest = "/opt/Modest/"

["byproducts"]
tmpfolder = "/tmp"
cleanup = 0